// import type { Metadata } from "next";  // there are important for the typeScript
import {Poppins } from "next/font/google";
import "./globals.css";
import { UserProvider } from './context/UserContext'
const popins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

// export const metadata: Metadata = {
//   title: "Muqeem",
//   description: "Generated by create next app",
// }; // there are used with the help of the typeSript 

//without typeScript 
export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={popins.className}>
        <UserProvider>
          {children}
        </UserProvider>

      </body>

    </html>
  );
}